[package]
name = "aemo-rs"
version = "0.2.0"
authors = ["Eric Sheppard <eric@eigenmo.de>", "Nayika Sheppard <nayika@eigenmo.de>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/esheppa/aemo-rs"
maintenance = { status = "experimental" }
description = "This library contains functions to read AEMO nemweb data files (zipped CSV files with one or more sub files inside) to Rust Structs"

[dependencies]
log = "0.4"
zip = "0.5"
csv = "1.1"
chrono-tz = "0.5"
thiserror = "1"
rust_decimal = "1.6"
rayon = "1.3"
futures = "0.3"
serde_json = "1"

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.chrono]
version = "0.4"
features = ["serde"]

[dependencies.clickhouse-rs]
version = "0.2.0-alpha.5"
optional = true

[dependencies.tiberius]
version = "0.4"
features = ["rust_decimal"]
optional = true

[dev-dependencies]
anyhow = "1"
serde_json = "1"
env_logger = "0.6"
tokio = { version = "0.2", features = ["full"] }
tokio-util = { version = "0.3", features = ["compat"] }
flate2 = "1"
# reqwest = "0.10"
# scraper = "0.10"

[workspace]
members = ["codegen"]

[features]
sql_server = ["tiberius"]
clickhouse = ["clickhouse-rs"]
ancillary_services = []
asoffer = []
bids = []
billing_config = []
billing_run = []
configuration = []
demand_forecasts = []
dispatch = []
force_majeure = []
gd_instruct = []
generic_constraint = []
historical = []
irauction = []
market_config = []
market_notice = []
mcc_dispatch = []
meter_data = []
mrevent = []
mtpasa = []
network = []
p5min = []
participant_registration = []
pdpasa = []
pre_dispatch = []
prudentials = []
reserve_data = []
settlement_config = []
settlement_data = []
stpasa_solution = []
trading_data = []
voltage_instructions = []
mmsdm = ["ancillary_services","asoffer","bids","billing_config","billing_run","configuration","demand_forecasts","dispatch","force_majeure","gd_instruct","generic_constraint","historical","irauction","market_config","market_notice","mcc_dispatch","meter_data","mrevent","mtpasa","network","p5min","participant_registration","pdpasa","pre_dispatch","prudentials","reserve_data","settlement_config","settlement_data","stpasa_solution","trading_data","voltage_instructions"]
default = ["dispatch"]
