[package]
name = "aemo-rs"
version = "0.1.0"
authors = ["Eric Sheppard <eric@eigenmo.de>", "Nayika Sheppard <nayika@eigenmo.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
env_logger = "0.6"
zip = "0.5"
structopt = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["arbitrary_precision"] }
chrono = { version = "0.4", features = ["serde"] }
chrono-tz = "0.5"
tokio = "^0.2"
csv = "1.1"
reqwest = "0.9"
scraper = "0.10"
clickhouse-rs = "*"
futures = "0.1.26"
rand = "*"
tokio-postgres = "0.5.0-alpha.2"
rayon = "1.3"