[package]
name = "aemo-rs"
version = "0.1.0"
authors = ["Eric Sheppard <eric@eigenmo.de>", "Nayika Sheppard <nayika@eigenmo.de>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/esheppa/aemo-rs"
maintenance = { status = "experimental" }

[dependencies]
log = "0.4"
zip = "0.5"
serde = { version = "1", features = ["derive"] }
csv = "1.1"
chrono = { version = "0.4", features = ["serde"] }
chrono-tz = "0.5"

[dev-dependencies]
serde_json = "1"
env_logger = "0.6"
reqwest = "0.9"
scraper = "0.10"
rayon = "1.3"

